name: Deploy site
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    # don't install it
    #  - name: Build/Package files
    #    if: ${{ always() && hashFiles('package.json') }}
    #    run: |
    #      docker build .  -f ./docker/Dockerfile  -o build

      - name: Remove unused files
        run: |
          rm -fr .idea docker

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }} # will be appended to existing .ssh/known_hosts
          config: StrictHostKeyChecking=no
      - name: Rsync files
        env:
          USER: ${{ secrets.USER }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # now ssh
          echo $REPO_NAME
          rsync -avz --delete --cvs-exclude . $USER@reyote.mnfurs.org:public_html/
      - name: Clear cache
        env:
          USER: ${{ secrets.USER }}
        run: |
          ssh $USER@reyote.mnfurs.org "echo 'sweet'"
